version: "3"

services:

  server:
    build: ./server
    ports:
      - 8000:8000
    environment:
      DB_URL: mongodb+srv://khewitt:${MONGO_PASS}@campbell-cluster.zto26tx.mongodb.net/?retryWrites=true&w=majority

  client:
    build: ./client
    ports:
      - 3000:3000
    
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - music-api:/data/db

volumes:
  music-api: 
